-- ENT Exam Hub — General station: Epistaxis case (SCFHS format, per-point marks).
-- Source: Pasha, Otolaryngology Head & Neck Surgery Clinical Reference Guide, 6th ed (epistaxis chapter).
-- Re-runnable; replaces the General station.
delete from public.exam_questions where station = 'General';
insert into public.exam_questions (station, question_id, ord, prompt, max_marks, model_answers, images) values
  ('General', 'Q0', 0, 'Case (read to the candidate): A 68-year-old man, hypertensive and on warfarin for atrial fibrillation, presents to the emergency department with profuse right-sided epistaxis for 2 hours not controlled by pinching.', 0, '[]'::jsonb, '[]'::jsonb),
  ('General', 'G1', 1, '[Anatomy · Senior] Describe the arterial supply and the common bleeding sites in epistaxis.', 8, '["Kiesselbach''s plexus (Little''s area) on the anterior septum — the commonest site (~90%) of epistaxis (3 marks)", "Contributing arteries: anterior ethmoidal (internal carotid → ophthalmic), superior labial (external carotid → facial), greater palatine and sphenopalatine (external carotid → maxillary) (3 marks)", "Woodruff''s plexus — posterolateral wall behind the inferior/middle turbinates; common source of posterior bleeds (sphenopalatine + ascending pharyngeal) (2 marks)"]'::jsonb, '[]'::jsonb),
  ('General', 'G2', 2, '[Anatomy · Senior] Differentiate anterior from posterior epistaxis and its significance.', 7, '["Anterior — commonest, usually Little''s area, often trauma/dryness, easier to control (3 marks)", "Posterior — sphenopalatine/Woodruff territory, often elderly, hypertensive or anticoagulated, bleeds into the throat, airway risk, harder to control (3 marks)", "Posterior bleeds may require posterior packing and airway monitoring (1 mark)"]'::jsonb, '[]'::jsonb),
  ('General', 'G3', 3, '[History] What do you ask in the history?', 8, '["Characterize the bleed — estimated blood loss, duration, intermittent versus continuous, and side (2 marks)", "Previous episodes (frequency, magnitude, need for packing) and inciting factors (nose-picking, vigorous blowing, trauma) (2 marks)", "Blood dyscrasias/comorbidity — hypertension, leukaemia, ITP, von Willebrand disease, renal/hepatic failure, haemophilia, HHT (2 marks)", "Medications and social history — antiplatelets (aspirin, NSAIDs), anticoagulants (warfarin, heparin), herbals (garlic, ginkgo, ginseng), cocaine, alcohol (2 marks)"]'::jsonb, '[]'::jsonb),
  ('General', 'G4', 4, '[History · Senior] What are the common causes and how do you frame the differential?', 7, '["Anterior epistaxis — trauma (nose-picking, vigorous blowing) and mucosal dehydration (dry/winter) are commonest (2 marks)", "Refractory epistaxis — hypertension, aspirin/antiplatelets and alcohol abuse; hypertension is a common cause of posterior epistaxis (3 marks)", "Use the KITTENS differential; suspect HHT (recurrent bleeds, telangiectasias) or a tumour (unilateral bleed with a mass; juvenile angiofibroma in adolescent males) (2 marks)"]'::jsonb, '[]'::jsonb),
  ('General', 'G5', 5, '[Examination] How do you assess and localize the bleed?', 7, '["Assess ABCs and vital signs, especially blood pressure (2 marks)", "Use adequate lighting (headlamp), nasal speculum, bayonet forceps and suction (Frazier/Yankauer); decongest with phenylephrine or oxymetazoline ± topical lidocaine (3 marks)", "Nasal endoscopy to localize the vessel/excoriation/foreign body/mass; examine the oropharynx for clot and active posterior bleeding (2 marks)"]'::jsonb, '[]'::jsonb),
  ('General', 'G6', 6, '[Investigations] What investigations would you order?', 5, '["PT/PTT, bleeding time, CBC, liver function tests, creatinine, type and screen (3 marks)", "INR (the patient is on warfarin) (1 mark)", "Imaging or endoscopy if a mass or foreign body is suspected (1 mark)"]'::jsonb, '[]'::jsonb),
  ('General', 'G7', 7, '[Management] Outline the initial acute management.', 8, '["Apply continuous pressure to the lower (cartilaginous) nose, sitting up with chin down so blood is spat out, not swallowed (3 marks)", "Apply a vasoconstrictor (phenylephrine/oxymetazoline) ± topical anaesthetic and localize the active bleeding site (2 marks)", "Resuscitate — correct hypovolaemia (3:1 crystalloid rule), strict blood-pressure control, and address coagulopathy (FFP, platelets, cryoprecipitate) (3 marks)"]'::jsonb, '[]'::jsonb),
  ('General', 'G8', 8, '[Management] Cauterization — indications and pitfalls?', 6, '["Cautery — chemical (silver nitrate), thermal or electric — for minor bleeding with a visible point in an accessible area (Kiesselbach''s plexus) (3 marks)", "It coagulates only the superficial vessel with a higher rebleed rate; NEVER cauterize both sides of the septum at the same point (risk of septal perforation/cartilage injury) (3 marks)"]'::jsonb, '[]'::jsonb),
  ('General', 'G9', 9, '[Management · Senior] What topical haemostatic options are available?', 6, '["Resorbable agents — gelatin (Gelfoam), oxidized cellulose (Surgicel), thrombin-gelatin matrix (Floseal), fibrin glue, microfibrillar collagen (2 marks)", "Topical tranexamic acid (antifibrinolytic; the IV form applied topically) (2 marks)", "Follow with nasal saline spray; may avoid non-absorbable packing (2 marks)"]'::jsonb, '[]'::jsonb),
  ('General', 'G10', 10, '[Management · Senior] Describe anterior nasal packing.', 10, '["Options — expandable sponge (Merocel), inflatable balloon (Rapid Rhino/Rhino Rocket), resorbable pack (NasoPore/Gelfoam), or Vaseline/iodoform strip-gauze laid to the posterior choanae (3 marks)", "Keep the pack in place 2–5 days to allow a mature thrombus (2 marks)", "Give antistaphylococcal antibiotics to reduce toxic shock syndrome, rhinosinusitis and otitis media (2 marks)", "Indication — acute/recurrent epistaxis after conservative measures or cautery; complications — obstruction, pressure necrosis of nasal/septal cartilage, hypoxia, rhinosinusitis, bacteraemia, epiphora (3 marks)"]'::jsonb, '[]'::jsonb),
  ('General', 'G11', 11, '[Management · Senior] Describe posterior nasal packing.', 10, '["Gauze/sponge/Foley/pneumatic catheter to close the choana, plus a formal anterior pack to create a closed tamponaded space; dual-balloon devices ease placement (3 marks)", "Indications — failed anterior packing, skull-base trauma, or haemorrhage from a major sphenopalatine branch (3 marks)", "Keep 2–4 days with antistaphylococcal antibiotics (1 mark)", "Risks — airway compromise (admit/monitor, ICU if bilateral), painful and needs cooperation, may need intubation/GA, eustachian tube dysfunction, alar necrosis, hypoxia (3 marks)"]'::jsonb, '[]'::jsonb),
  ('General', 'G12', 12, '[Management · Senior] What are the surgical and interventional options for refractory epistaxis?', 10, '["Endoscopic sphenopalatine artery (SPA) ligation — preferred for intractable posterior epistaxis; ligate at the sphenopalatine foramen (landmark: crista ethmoidalis) (4 marks)", "Anterior/posterior ethmoidal artery ligation (endoscopic or external Lynch approach) for intractable anterior/high bleeds; maxillary or external carotid artery ligation as a last resort for life-threatening bleeding (3 marks)", "Embolization of the distal internal maxillary/sphenopalatine artery — for intractable (usually posterior), surgically inaccessible, or non-operative/coagulopathic patients; risks include stroke/embolic event and facial pain (3 marks)"]'::jsonb, '[]'::jsonb),
  ('General', 'G13', 13, '[Management · Senior] How would you manage HHT, and what preventive measures apply?', 8, '["Hereditary haemorrhagic telangiectasia (Osler-Weber-Rendu, autosomal dominant) — friable mucosa with telangiectasias; manage with laser/cautery ablation, embolization, septodermoplasty or Young''s procedure; medical options tamoxifen, estrogens, bevacizumab (4 marks)", "Prevention/chronic care — nasal hygiene and moisture (saline, petroleum ointment, humidity), long-term blood-pressure control, avoid local trauma (picking, blowing, straining), and aim intranasal sprays away from the septum (4 marks)"]'::jsonb, '[]'::jsonb);
