-- ENT Exam Hub — General 2 station: Deep neck infection / quinsy (SCFHS format, per-point marks).
-- Re-runnable; replaces the General 2 station.
delete from public.exam_questions where station = 'General 2';
insert into public.exam_questions (station, question_id, ord, prompt, max_marks, model_answers, images) values
  ('General 2', 'Q0', 0, 'Case (read to the candidate): A 24-year-old man presents with 4 days of worsening sore throat, now with severe odynophagia, trismus, a muffled hot-potato voice, drooling and fever. He can barely open his mouth.', 0, '[]'::jsonb, '[]'::jsonb),
  ('General 2', 'N1', 1, '[History] What do you ask in the history?', 7, '["Onset and progression of the sore throat; severe odynophagia/dysphagia (2 marks)", "Trismus (reduced mouth opening), muffled voice, drooling, referred otalgia (2 marks)", "Fever/rigors, neck swelling/stiffness, preceding tonsillitis or dental infection (2 marks)", "Risk factors — diabetes, immunosuppression, IV drug use (1 mark)"]'::jsonb, '[]'::jsonb),
  ('General 2', 'N2', 2, '[History · Senior] What red-flag, airway-threatening features must you elicit?', 5, '["Difficulty breathing, stridor, inability to swallow secretions (drooling) (2 marks)", "Neck stiffness, chest pain/dyspnoea (mediastinitis), rapidly enlarging neck swelling (2 marks)", "Voice change with respiratory distress signalling impending obstruction (1 mark)"]'::jsonb, '[]'::jsonb),
  ('General 2', 'N3', 3, '[Examination] How do you examine this patient?', 8, '["General — toxic/septic appearance, vital signs, sepsis screen (2 marks)", "Oropharynx — unilateral peritonsillar swelling, tonsil displaced medially, uvula deviated to the opposite side, trismus limiting the view (3 marks)", "Neck — tender jugulodigastric lymphadenopathy, induration/swelling, crepitus (2 marks)", "Airway — stridor/drooling; flexible nasendoscopy to assess the supraglottis if safe (1 mark)"]'::jsonb, '[]'::jsonb),
  ('General 2', 'N4', 4, '[Examination · Senior] How do you assess airway threat and severity?', 7, '["Recognize impending airway compromise — stridor, tripod position, drooling, agitation/hypoxia (3 marks)", "Do NOT lie the patient flat or over-examine if the airway is threatened; keep upright and call senior + anaesthetics (2 marks)", "Flexible fibreoptic laryngoscopy for supraglottic/laryngeal involvement; prepare for a difficult airway (2 marks)"]'::jsonb, '[]'::jsonb),
  ('General 2', 'N5', 5, '[Anatomy · Senior] Describe the deep neck spaces relevant to these infections.', 12, '["Peritonsillar space — between the tonsil capsule and superior constrictor; quinsy is the commonest deep-neck abscess (3 marks)", "Parapharyngeal (lateral pharyngeal) space — anterior muscular and posterior neurovascular (carotid sheath, CN IX–XII) compartments (3 marks)", "Retropharyngeal space and the danger space — potential spread to the mediastinum (3 marks)", "Submandibular/sublingual spaces — Ludwig''s angina (3 marks)"]'::jsonb, '[]'::jsonb),
  ('General 2', 'N6', 6, '[Investigations] What investigations would you order?', 8, '["Bloods — CBC, CRP, glucose, U&E, blood cultures, group and save (3 marks)", "Pus/throat swab and culture (aerobes and anaerobes; often polymicrobial) (2 marks)", "Contrast CT of the neck — the key study (extent, abscess vs cellulitis, spaces, airway, mediastinal extension) (3 marks)"]'::jsonb, '[]'::jsonb),
  ('General 2', 'N7', 7, '[Investigations] How do you interpret the imaging?', 5, '["CT with contrast — a ring-enhancing low-density collection indicates an abscess; assess size, spaces, gas and airway (2 marks)", "Lateral neck X-ray (in children) — widened prevertebral soft tissue suggests a retropharyngeal collection (2 marks)", "Ultrasound can guide aspiration of superficial collections (1 mark)"]'::jsonb, '[]'::jsonb),
  ('General 2', 'N8', 8, '[Management] Outline the management of the peritonsillar abscess (quinsy).', 8, '["Resuscitate — IV access, fluids, analgesia, antipyretics; secure the airway if threatened (2 marks)", "IV antibiotics covering Streptococcus and anaerobes (e.g. benzylpenicillin + metronidazole, or co-amoxiclav) ± steroids (3 marks)", "Drainage — needle aspiration or incision and drainage at the point of maximal bulge (3 marks)"]'::jsonb, '[]'::jsonb),
  ('General 2', 'N9', 9, '[Management] Describe the aspiration/drainage technique and its pitfalls.', 6, '["Local anaesthetic; aspirate the most fluctuant point with a needle guard (the carotid lies ~2.5 cm posterolateral) (3 marks)", "Send pus for culture; consider interval or hot tonsillectomy in recurrent/selected cases (2 marks)", "Admit for IV antibiotics and reassess; most resolve with drainage + antibiotics (1 mark)"]'::jsonb, '[]'::jsonb),
  ('General 2', 'N10', 10, '[Management] What are the complications of quinsy or failed treatment?', 6, '["Spread to the parapharyngeal/retropharyngeal spaces (deep neck infection) (3 marks)", "Airway obstruction, aspiration, recurrence (2 marks)", "Lemierre''s syndrome (Fusobacterium, internal jugular vein thrombophlebitis with septic emboli) (1 mark)"]'::jsonb, '[]'::jsonb),
  ('General 2', 'N11', 11, '[Management · Senior] How do you manage an established deep neck space infection?', 10, '["ABCDE with early airway control — low threshold for awake fibreoptic intubation or surgical airway, with senior anaesthetic and ENT involvement (3 marks)", "IV broad-spectrum antibiotics (Streptococcus, anaerobes, Staphylococcus); fluids; control diabetes (3 marks)", "Surgical drainage (transcervical or transoral) for abscesses of about 2–2.5 cm or more, or non-responders; send cultures (3 marks)", "Identify and treat the source (dental, tonsillar, salivary) (1 mark)"]'::jsonb, '[]'::jsonb),
  ('General 2', 'N12', 12, '[Management · Senior] What are the major complications of deep neck infection?', 10, '["Airway obstruction — the commonest cause of death (2 marks)", "Descending mediastinitis (retropharyngeal/danger-space spread) — high mortality; needs CT chest and thoracic drainage (3 marks)", "Vascular — carotid artery erosion/rupture, internal jugular vein thrombosis (Lemierre''s), septic emboli (3 marks)", "Cranial neuropathies, cavernous sinus thrombosis, necrotizing fasciitis, sepsis (2 marks)"]'::jsonb, '[]'::jsonb),
  ('General 2', 'N13', 13, '[Management · Senior] Describe Ludwig''s angina and its management.', 8, '["Bilateral cellulitis of the submandibular and sublingual spaces, usually odontogenic (lower molars) (2 marks)", "Brawny floor-of-mouth swelling with tongue elevation/protrusion and rapid airway compromise (3 marks)", "Secure the airway early (often awake fibreoptic or tracheostomy), IV antibiotics, drainage, and dental source control (3 marks)"]'::jsonb, '[]'::jsonb);
